CREATE TABLE `affiliateProducts` (
	`id` varchar(64) NOT NULL,
	`productId` varchar(128),
	`asin` varchar(32),
	`name` text,
	`description` text,
	`pricing` text,
	`affiliateUrls` text,
	`imageUrl` text,
	`category` varchar(64),
	`eventTypes` text,
	`rating` decimal(2,1),
	`reviews` varchar(32),
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()),
	CONSTRAINT `affiliateProducts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `worldTriathlonEvents` (
	`id` varchar(64) NOT NULL,
	`eventId` varchar(128),
	`source` varchar(32),
	`countryCode` varchar(2),
	`title` text,
	`description` text,
	`metaDescription` text,
	`venue` text,
	`city` varchar(128),
	`region` varchar(128),
	`country` varchar(128),
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`date` timestamp,
	`finishDate` timestamp,
	`registrationDeadline` timestamp,
	`eventType` varchar(32),
	`categories` text,
	`specifications` text,
	`registrationUrl` text,
	`officialWebsite` text,
	`worldTriathlonUrl` text,
	`faqSchema` text,
	`recommendedProducts` text,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()),
	`lastSyncedAt` timestamp,
	`published` boolean NOT NULL DEFAULT true,
	CONSTRAINT `worldTriathlonEvents_id` PRIMARY KEY(`id`)
);
