/**
 * Awin 365Rider Banner Component
 * 
 * ⚠️ TO UPDATE THE BANNER: Edit /client/src/config/affiliateConfig.tsx
 * DO NOT edit this file directly!
 */

import { AWIN_BANNER_CONFIG } from '@/config/affiliateConfig';

interface AwinBannerProps {
  className?: string;
}

export default function AwinBanner({ className = '' }: AwinBannerProps) {
  return (
    <div className={`flex justify-center items-center ${className}`}>
      <a 
        rel="sponsored" 
        href={AWIN_BANNER_CONFIG.clickUrl}
        target="_blank"
        className="block hover:opacity-90 transition-opacity"
      >
        <img 
          src={AWIN_BANNER_CONFIG.imageUrl}
          alt={AWIN_BANNER_CONFIG.altText}
          className="max-w-full h-auto"
        />
      </a>
    </div>
  );
}
